### ISSUE TITLE
The data hazards project link is broken

### ISSUE THREAD

**Issue by Lextuga007** [realworlddatascience/realworlddatascience.github.io#56]
At the bottom of this page https://realworlddatascience.net/viewpoints/editors-blog/posts/2023/08/06/jsm-blog.html#wednesday-august-9 the link goes to page 404. Just checking this is the https://datahazards.com/ too 😃

**Comment by brtarran** [comment]
Fixed in 6ec1f6d. @Lextuga007, if you have a contact at the project, you might want to let them know that the error was in the sharing code on the Better Images of AI site, so the issue will be replicated for anyone else who uses the code. Problem was missing https:// in the URL within the <a href> tags.

**Comment by Lextuga007** [comment]
Thanks! Yes I do have contact with the project owners and I'll let them know. Prompted from seeing the image I've suggested they may wish to get in touch to contribute to the site 😃

**Comment by brtarran** [comment]
@all-contributors
please add @Lextuga007 for bug.
